AgileGroup6/Agile-Project

- .github/pull_request_template.md
- README.md
to add the Figma basic app 
- added the PR template in .github as suggested [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- added Figma link to readme 
- just tested readme
>  added pullrequrest template and figma to readme file

- .github/ISSUE_TEMPLATE/base-template-for-issues.md
> Update issue templates

- .gitignore
- server/app/config.js
- server/app/db/doThing.js
- server/app/db/pool.js
- server/app/package-lock.json
- server/app/package.json
- server/app/server.js
- Closes #57
- updated .gitignore to hide server secrets
- added db/pool.js to handle database connections
- Ran local server with `npm run dev`
> Setup node database objects and sample files

- client/app/src/components/browseResults.vue
- client/app/src/components/ingredientCard.vue
- client/app/src/views/BrowseView.vue
Move progress on issue #60 into main sub branch
Added two columns of data with dummy data to show the base layout
Tested on localhost with NPM server
> 60 display relevant items when a category is selected

- server/app/api/allRecipes.js
- server/app/api/ping.js
- server/app/db/getAllRecipes.js
- server/app/routes.js
- Create api endpoint to return al recipes that the database stores
- Added allRecipes endpoint
- Ran on local server, works as expected
> added allRecipes endpoint

- database/Dockerfile
- docker-compose.yml
- Closes #56 
- Updated docker and docker-compose files
- Ran on local server and machine
> Added docker container for mariadb instance

- database/init/3_user.sql
- docker-compose.yml
- server/app/config.js
- Allow project to be built and deployed with docker-compose on remote server
- Closes #97 
- Modified backend host for production build to docker database container
- Fixed error in sql
- tested using `docker-compose up --force-recreate --build`
> integreated docker fully with project

- server/app/server.js
- Closes #100 
- Modified server.js to always enable CORS 
- Tested on VPS
> Enabled cors for production mode

- client/app/src/App.vue
fix issues with vue build
changes image directory
tested with images on local host
> Vue build fix

- client/app/src/components/admin/LogOut.vue
- client/app/src/components/homePage/ButtonComponent.vue
- client/app/src/views/Admin.vue
fixes the connections between admin page and home
made the hrefs work
tested on local host
> links working in order

- client/app/src/components/admin/BigButton.vue
- client/app/src/components/admin/LogOut.vue
- client/app/src/views/AddRecipe.vue
- client/app/src/views/Admin.vue
closes #102
fixes the buttons and links on the admin page allowing use of add recipe page and making the buttons the same as other pages
tested on local host
> Fix links and buttons admin

- client/app/src/App.vue
- client/app/src/components/admin/LogOut.vue
- client/app/src/views/AddRecipe.vue
- client/app/src/views/Admin.vue
- client/app/src/views/AdminLogin.vue
> Styling fixes and fixed login feature on admin page

- client/app/src/components/homePage/IngredientSearch.vue
- client/app/src/components/homePage/ShoppingList.vue
- client/app/src/views/HomePage.vue
Tracked by #35 closes issue #114, #115, #116. Minimum working version of shopping list, request to merge with dev-stable
Search bar now adds to shoppingList component once the search button is pressed. Checkbox is present for each item.  
Delete button for each item is not present/functioning must come back to it at a later date. Making request now prior to the v1.0 milestone
Tested on local server with npm.
> Shopping list

- client/app/src/views/RemoveRecipe.vue
So npm will build succesfully
updated logo link
'npm run bui;d'
> updated logo link

- client/app/src/views/HomePage.vue
fix npm build issue
binding to variable
tested on npm and python server
> fixed build issue

- client/app/src/App.vue
- client/app/src/components/browseAll/ingredientCard.vue
- client/app/src/router/index.js
- client/app/src/views/AddRecipe.vue
- client/app/src/views/BrowseView.vue
- client/app/src/views/RecipePage.vue
> Browse ingredients fixed grid

- server/app/db/getSingleRecipe.js
- Closes #174 
- returned serves value in json response
- tested on local server
> /api/getRecipe will return served value

- client/app/src/stores/RecipeStore.js
- client/app/src/views/HighlightRecipe.vue
front and back end of highlight recipes 
closes #150 
added back end functionality, now selects correct recipes and sends date wanted to schedule
tested on local host
> Schedule admin connect f+b

- client/app/src/components/homePage/ShoppingList.vue
- client/app/src/stores/ingridentsStore.js
To make dev-stable stable again.
Caused by merge issue spawned from #176
Fixed issue that made styling mess up te home page.
Tested on localhost
> Bugfix to styling changes

- client/app/src/views/RecipePage.vue
- Select all ingredients added to recipe page.
- Updated RecipePage.vue
- Ran on local server
> Added Select All to to recipe page

- client/app/src/components/homePage/ShoppingList.vue
Fixes #194
Fixes spacing error described in Issue #194 
Made checkboxes bigger for more accessibility 
- Local NPM Server
- `NPM run build`
> Shopping List spacing fix

- .github/workflows/node.js.yml
- client/app/package.json
- client/app/src/tests/ingridentsstore.test.js
- client/app/vitest.config.ts
Introducing automated testing. 
added a basic test and automated testing for `npm run build` 
the the checks tab of this PR
> Automated test introduction 

- client/app/src/components/homePage/ShoppingList.vue
Closes #199 and #200
Finishes story #190 
Added a clear all button that removes all items
Added a warning requiring a confirmation to remove all items
Added a title to the shopping list
Added text that displays when the shopping list is empty
Localhosted NPM server
`NPM run build` ran with no issues
Tested buttons for functionality and all use cases
> Delete and clear

- client/app/src/views/RecipePage.vue
- Closes #11 
- Share button that copies URL to clipboard.
- Add ingredients to shopping basket button.
- Changed styling on textarea
- Ran on local server
> Finished RecipePage.vue

- client/app/src/views/RecipePage.vue
- Fixed bug on recipe page
- button goes to correct place now.
- Ran on local server.
> Quick improvement to recipePage

- server/app/db/recipeFinder.js
- title
- added LIMIT 5 to sql query
- locally
> Limit find recipe response to 5

- client/app/src/components/browseRecipes/RecipeCard.vue
- client/app/src/router/index.js
- client/app/src/views/BrowseAllRecipes.vue
- client/app/src/views/HomePage.vue
Closes user story #201 
Added link to browse all recipes to home page.
Introduces Browse all recipes page.
Adds Recipe Card component. 
Tested locally using npm localhost server.
> Browse recipes view

- client/app/src/components/homePage/BasketRecipe.vue
- client/app/src/components/homePage/FavouriteRecipe.vue
- client/app/src/stores/RecipeStore.js
- client/app/src/views/HomePage.vue
add recommended recipes basked on basket
integrated the basket recommendations 
locally on npm
> added recomendations to the home page based on basket

- client/app/src/components/browseRecipes/RecipeCard.vue
this adds the functionality to take you to the specific recipe page from the browse all recipes
add router link to the individual recipe cards
tested locally on npm
> added link to all recipes in the browse all recipes page

- client/app/src/tests/RecipeStore.test.js
- client/app/src/tests/ingridentsstore.test.js
needed to add more tests to make sure the data integrity is maintained 
added recipe store tests
ran tests locally and ran npm build run
> Added additional tests 

- client/app/src/components/homePage/FavouriteRecipe.vue
- client/app/src/components/homePage/ListItem.vue
- client/app/src/config.js
- client/app/src/stores/ingridentsStore.js
- client/app/src/views/HomePage.vue
introducing an image API to get images. 
fixing the watch to watch the store reference to be called on when the shopping list changes 
watch the object to watch the shopping list, ref 
ran local test 
ran npm run build
> Added one image automation to highlighted recipes and bug fix for shopping list watch 

- client/app/src/components/homePage/FavouriteRecipe.vue
- client/app/src/views/HomePage.vue
Removed api images
Removed api images
> Removed api images

- client/app/package.json
- client/app/src/App.vue
- client/app/src/stores/passwordStore.js
- client/app/src/views/Admin.vue
- client/app/src/views/AdminLogin.vue
- server/app/api/checkAdminPassword.js
- server/app/routes.js
- Make it so only the admin can login to the website and access restricted pages
- Closes #120; Closes #119
- Admin password is saved as a cookie
- Added admin button on top right of root page
- Added authentication middleware to api routes
- Tested persistence of cookie, by restarting browser
- Tested running on local machine connection to the lgl.caydey.com/api VPS api
> Integrated the admin login page with backend

- client/app/src/assets/asset_images.js
- client/app/src/views/RecipePage.vue
added images assets json and added scoped styling from recipe page
added images assets json and added scoped styling from recipe page
locally npm
> added images assets json and added scoped styling from recipe page

- client/app/src/components/remove/RemoveCard.vue
- client/app/src/views/RemoveRecipe.vue
All recipes are displayed in cards with a remove button- should work properly just need API call implemented
Local npm run
> Remove recipe work

- client/app/src/views/HighlightRecipe.vue
- Fix api error when scheduling recipe
- Fixed typo in url
- Locally
> Admin schedule recipe

- database/init/1_tables.sql
- server/app/api/removeRecipe.js
- server/app/db/delRecipe.js
- server/app/routes.js
- Added API endpoint for removing recipe
- Allowed cascade deletion on sql tables
- locally
> Api remove recipe

- client/app/src/components/homePage/FavouriteRecipe.vue
carousel requires at least one active card so it needed and index 
declared and get index from recpie items 
npm run build and local testing
> [Quick Fix] Index not declared 

- client/app/src/components/remove/RemoveCard.vue
- client/app/src/views/RemoveRecipe.vue
> Remove recipe finished

- server/app/api/removeRecipe.js
- server/app/db/delRecipe.js
- Fix error when calling removeRecipe api endpoint
- Fixed bug
- locally and on master server
> [Bug Fix] : removeRecipe api endpoint when id is not set

- client/app/src/components/browseRecipes/RecipeCard.vue
- client/app/src/components/homePage/AllergyNotice.vue
- client/app/src/components/homePage/IngredientSearch.vue
- client/app/src/views/AllergyPage.vue
Closes issue #256
Closed unscoped style tags. 
Makes image in browseAllRecipe page scale on screen size.
Tested locally on npm
> [BugFix] BrowseAllIngredients scales images

- client/app/src/views/RecipePage.vue
fix bug where the items are available but they seem like they are not
made sure to find the ingrident first before adding to store 
made sure to use store.addItem to avoid spam 
ran tests locally and also ran build
> [Bug Fix] : recipes getting added as not in shop 

- server/app/api/setFeatured.js
- Allow setFeatured api endpoint to work with frontend
- Changed params of setFeatured
- locally tested
> adjusted setFeatured params
